language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef --notests installdeps .
  - zef-build
  # - panda --notest install LWP::Simple

script:
  - PERL6LIB=lib prove -e perl6 -vr t/
sudo: false
